### ISSUE TITLE
Ships spawning on land and ports not spawning on a dual core processor.

### ISSUE THREAD

**Issue by smeagle42** [JPII/NavalBattle#236] opened 2013-04-17 18:42 UTC
Dual core processor computers don't spawn ports and spawn entities on land.

**Comment by ThomasGaubert** [comment] 2013-04-17 18:45
I'm fairly sure this doesn't affect all dual core CPUs.

**Comment by maximusvladimir** [comment] 2013-04-18 01:54
This has to do with thread execution.

"It's not gonna be an easy fix." - Iron Man 2 quote.
![Iron Man 2](http://www.themarysue.com/wp-content/uploads/2013/01/nick-fury-im2.jpg)

**Comment by abauer** [comment] 2013-04-18 02:54
unless it affects multitudes of users this really shouldn't be a top-priority

**Comment by ThomasGaubert** [comment] 2013-04-18 03:47
Might be related to #232

**Comment by maximusvladimir** [comment] 2013-04-18 12:43
"Might be related to #232"

It is related to 232.

**Comment by ThomasGaubert** [comment] 2013-04-18 14:05
Well okay.

**Comment by maximusvladimir** [comment] 2013-04-18 15:23
I didn't intend that to be so harsh. Sorry.

**Comment by ThomasGaubert** [comment] 2013-04-18 16:49
It's fine, I didn't take it that way.

**Comment by ThomasGaubert** [comment] 2013-05-06 16:47
Zach, check the current.jar and see if it works. It "fixed" my issues on my desktop.

**Comment by abauer** [comment] 2013-05-06 17:49
additionally we are going to be distributing via jar so if it works it 'solves' our problem

**Comment by ThomasGaubert** [comment] 2013-05-08 03:20
@smeagle42 please answer.

**Comment by ThomasGaubert** [comment] 2013-05-09 15:18
Closing for now.

**Comment by maximusvladimir** [comment] 2013-05-09 15:23
I just spoke with Mr. Smileg this morning, and he said this issue is still apparent.

**Comment by ThomasGaubert** [comment] 2013-05-09 16:01
I'm assuming this means with the .jar?

**Comment by maximusvladimir** [comment] 2013-05-10 02:11
Apparently he is having issues with the jar as well.

Can @smeagle42 confirm this?

**Comment by smeagle42** [comment] 2013-05-10 17:54
yes

**Comment by smeagle42** [comment] 2013-05-10 17:58
**Redacted**

**Comment by ThomasGaubert** [comment] 2013-05-10 18:09
Removed inappropriate comment. Please keep it clean.

**Comment by ThomasGaubert** [comment] 2013-05-10 18:09
@smeagle42

**Comment by maximusvladimir** [comment] 2013-05-15 12:49
The root cause of this is multithreading. The direct cause however, is the miss-assignment of tiles. I will look at shortly.

**Comment by maximusvladimir** [comment] 2013-05-15 13:01
I recently committed what I hoped to be a temporary fix. @smeagle42 do you want to test this fix?

**Comment by ThomasGaubert** [comment] 2013-05-16 16:30
Obviously not. Moved back and closed.

Reopen if the issue still exists.

**Closed as completed by ThomasGaubert** 2013-05-16 16:31 UTC
Labels: bug, grid/terrain/rendering, gameplay, max-top-priority

**Comment by maximusvladimir** [comment] 2013-05-16 16:54
I'm just worried it isn't going to work on Schram's computer.
