### ISSUE TITLE
There are ALOT of packages. Could we consider clearing some out???

### ISSUE THREAD

**Issue by maximusvladimir** [JPII/NavalBattle#78] opened 2012-12-06 23:24 UTC
I can clear out com.jpii.navalbattle.renderer, once I finish Pavo.

Y'all can delete com.jpii.dagen, com.jpii.dagen.processing, com.jpii.dagen.test, and com.jpii.dagen.vegetation. (MBBT).

Anything that y'all think could think of?

**Comment by ThomasGaubert** [comment] 2012-12-07 02:17
Is the problem being there are more sub-packages than necessary? (Anything beyond com.jpii.navalbattle.parent)

**Comment by abauer** [comment] 2012-12-07 15:25
i don't think the problem is a lot of packages (they create organization) i think there are some things that are packaged incorrectly and some packages that are not needed

**Comment by ThomasGaubert** [comment] 2012-12-07 15:44
I agree with @abauer. We can possibly discuss it whenever we decide to do the "check up" chat.

**Comment by maximusvladimir** [comment] 2012-12-07 15:50
Like I said;

Y'all can delete com.jpii.dagen, com.jpii.dagen.processing, com.jpii.dagen.test, and com.jpii.dagen.vegetation. (MBBT).

There might be a few others that we can optimize.

**Comment by abauer** [comment] 2012-12-07 18:03
having a tree flow diagram of the packages w/classes contained in them can help us organize during our checkupchat

**Comment by maximusvladimir** [comment] 2012-12-07 19:00
Does anyone have a copy Microsoft Office Visio??? Lucid charts is fine, but I really like Visio.

**Comment by ThomasGaubert** [comment] 2012-12-08 00:48
Sadly, no I don't.

**Comment by ThomasGaubert** [comment] 2012-12-12 02:08
Work will be carried out here: https://docs.google.com/spreadsheet/ccc?key=0AmzQhfjZvZcwdFdTdVJtMnFWaFljNld5eDAtaVZCNkE

cc: @maximusvladimir @abauer @smeagle42 @DarkWarHero @smeagle42

**Comment by ThomasGaubert** [comment] 2013-01-09 17:12
Closed as this is addressed in #98

**Closed as completed by ThomasGaubert** 2013-01-09 17:12 UTC
Labels: management, on hold
